spring:
  application:
    name: booking-api
  datasource:
    url: jdbc:h2:mem:localdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: ${PORT:8081}